# Let's start with the basics: this is a PHP project
language: php

# Run on top of a few versions to check compatibility
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

# And now, the moment of truth. Run PHPUnit tests
script: phpunit
